JOIN-MESSAGE:
  - '&5&m-----------------------------'
  - '&dWelcome to &e&lFlame Hub Core'
  - ''
  - '&eWelcome yourself and visit other servers'
  - 'Using our &6Server Navigator&e!'
  - '&5&m-----------------------------'
